name: release
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npx semantic-release
